[alias]
kbuild = """build --target x86_64-bird_os.json -Z build-std=core \
    -Z build-std-features=compiler-builtins-mem"""
kcheck = """check --target x86_64-bird_os.json -Z build-std=core \
    -Z build-std-features=compiler-builtins-mem"""
kdoc = """doc --target x86_64-bird_os.json -Z build-std=core \
    -Z build-std-features=compiler-builtins-mem"""
kclippy = """clippy --target x86_64-bird_os.json -Z build-std=core \
    -Z build-std-features=compiler-builtins-mem"""
krun = """run --package builder"""